"""Essence identities and planned powers supplied by the game designer."""
ESSENCES = [{'slug': 'essence-dark',
  'name': 'Dark Essence',
  'powers': {'signature': {'name': 'Shadow Leap',
                           'description': 'teleport through nearby shadows',
                           'implemented': False},
             'secondary': {'name': 'Shadow Veil',
                           'description': 'conceal yourself and become harder to hit',
                           'implemented': False},
             'passive': {'name': 'Dark Sight',
                         'description': 'see through darkness and concealment',
                         'implemented': False}}},
 {'slug': 'essence-holy',
  'name': 'Holy Essence',
  'powers': {'signature': {'name': 'Smite',
                           'description': 'empowered strike, devastating to corrupted foes',
                           'implemented': False},
             'secondary': {'name': 'Sanctuary',
                           'description': 'protective area around the party',
                           'implemented': False},
             'passive': {'name': 'Purification',
                         'description': 'resistance to curses, poison and corruption',
                         'implemented': False}}},
 {'slug': 'essence-magic',
  'name': 'Magic Essence',
  'powers': {'signature': {'name': 'Arcane Bolt',
                           'description': 'reliable raw magical attack',
                           'implemented': False},
             'secondary': {'name': 'Blink', 'description': 'short-range teleport', 'implemented': False},
             'passive': {'name': 'Spellcraft',
                         'description': 'improves magical abilities and orb interactions',
                         'implemented': False}}},
 {'slug': 'essence-sin',
  'name': 'Sin Essence',
  'powers': {'signature': {'name': 'Temptation',
                           'description': 'manipulate an enemy into making a poor action',
                           'implemented': False},
             'secondary': {'name': 'Indulgence',
                           'description': 'gain powerful temporary benefits at a later cost',
                           'implemented': False},
             'passive': {'name': 'Forbidden Knowledge',
                         'description': 'increased power with increasing risk/corruption',
                         'implemented': False}}},
 {'slug': 'essence-light',
  'name': 'Light Essence',
  'powers': {'signature': {'name': 'Radiant Beam',
                           'description': 'piercing beam that exposes enemies',
                           'implemented': False},
             'secondary': {'name': 'Flash', 'description': 'blind nearby enemies', 'implemented': False},
             'passive': {'name': 'True Sight',
                         'description': 'improves detection and reveals hidden things',
                         'implemented': False}}},
 {'slug': 'essence-swift',
  'name': 'Swift Essence',
  'powers': {'signature': {'name': 'Flurry',
                           'description': 'several rapid attacks',
                           'implemented': False},
             'secondary': {'name': 'Dash',
                           'description': 'rapidly reposition without a normal movement cost',
                           'implemented': False},
             'passive': {'name': 'Quick Reflexes',
                         'description': 'increased dodge and action speed',
                         'implemented': False}}},
 {'slug': 'essence-fire',
  'name': 'Fire Essence',
  'powers': {'signature': {'name': 'Fireball',
                           'description': 'explosive area damage',
                           'implemented': False},
             'secondary': {'name': 'Ignite',
                           'description': 'inflict a persistent burn',
                           'implemented': False},
             'passive': {'name': 'Fervor',
                         'description': 'dealing damage builds increasing offensive momentum',
                         'implemented': False}}},
 {'slug': 'essence-ice',
  'name': 'Ice Essence',
  'powers': {'signature': {'name': 'Freeze',
                           'description': 'temporarily immobilize a target',
                           'implemented': False},
             'secondary': {'name': 'Ice Armor',
                           'description': 'protective layer that can absorb damage',
                           'implemented': False},
             'passive': {'name': 'Cold Blooded',
                         'description': 'resistance to slows and control effects',
                         'implemented': False}}},
 {'slug': 'essence-blood',
  'name': 'Blood Essence',
  'powers': {'signature': {'name': 'Bloodletting',
                           'description': 'powerful attack that inflicts bleed',
                           'implemented': False},
             'secondary': {'name': 'Blood Sacrifice',
                           'description': 'spend HP for immediate power',
                           'implemented': False},
             'passive': {'name': 'Blood Drinker',
                         'description': 'recover health from bleeding enemies',
                         'implemented': False}}},
 {'slug': 'essence-lightning',
  'name': 'Lightning Essence',
  'powers': {'signature': {'name': 'Chain Lightning',
                           'description': 'jumps between multiple enemies',
                           'implemented': False},
             'secondary': {'name': 'Lightning Step',
                           'description': 'instant high-speed reposition',
                           'implemented': False},
             'passive': {'name': 'Overcharge',
                         'description': 'attacks occasionally shock or interrupt',
                         'implemented': False}}},
 {'slug': 'essence-death',
  'name': 'Death Essence',
  'powers': {'signature': {'name': 'Reap',
                           'description': 'execution attack against critically wounded enemies',
                           'implemented': False},
             'secondary': {'name': 'Raise Dead',
                           'description': 'temporarily animate a fallen enemy',
                           'implemented': False},
             'passive': {'name': 'Death Sense',
                         'description': 'detect wounded, dying and undead creatures',
                         'implemented': False}}},
 {'slug': 'essence-life',
  'name': 'Life Essence',
  'powers': {'signature': {'name': 'Regeneration',
                           'description': 'strong healing over time',
                           'implemented': False},
             'secondary': {'name': 'Entangle',
                           'description': 'living growth restrains enemies',
                           'implemented': False},
             'passive': {'name': 'Vitality',
                         'description': 'increased healing received and natural recovery',
                         'implemented': False}}},
 {'slug': 'essence-balance',
  'name': 'Balance Essence',
  'powers': {'signature': {'name': 'Equalize',
                           'description': 'redistribute health between targets',
                           'implemented': False},
             'secondary': {'name': 'Reversal',
                           'description': 'turn an enemy advantage against them',
                           'implemented': False},
             'passive': {'name': 'Equilibrium',
                         'description': 'bonuses become stronger the farther you are from a balanced '
                                        'state',
                         'implemented': False}}},
 {'slug': 'essence-pure',
  'name': 'Pure Essence',
  'powers': {'signature': {'name': 'Perfect Strike',
                           'description': 'removes damage RNG and produces a precise result',
                           'implemented': False},
             'secondary': {'name': 'Purify',
                           'description': 'remove harmful effects',
                           'implemented': False},
             'passive': {'name': 'Refinement',
                         'description': 'reduce ability costs and equipment degradation',
                         'implemented': False}}},
 {'slug': 'essence-wind',
  'name': 'Wind Essence',
  'powers': {'signature': {'name': 'Gust',
                           'description': 'push several enemies and disrupt formations',
                           'implemented': False},
             'secondary': {'name': 'Wind Step',
                           'description': 'highly mobile evasive movement',
                           'implemented': False},
             'passive': {'name': 'Featherweight',
                         'description': 'reduced movement penalties and improved evasion',
                         'implemented': False}}},
 {'slug': 'essence-water',
  'name': 'Water Essence',
  'powers': {'signature': {'name': 'Undertow',
                           'description': 'pull/reposition enemies',
                           'implemented': False},
             'secondary': {'name': 'Flow',
                           'description': 'redirect or partially avoid an incoming attack',
                           'implemented': False},
             'passive': {'name': 'Adaptation',
                         'description': 'repeated exposure to a damage/effect type gradually improves '
                                        'resistance',
                         'implemented': False}}},
 {'slug': 'essence-earth',
  'name': 'Earth Essence',
  'powers': {'signature': {'name': 'Stonewall',
                           'description': 'massively increase defense temporarily',
                           'implemented': False},
             'secondary': {'name': 'Tremor',
                           'description': 'knock down/disrupt a group of enemies',
                           'implemented': False},
             'passive': {'name': 'Unmovable',
                         'description': 'resist knockback, stagger and physical control',
                         'implemented': False}}},
 {'slug': 'essence-might',
  'name': 'Might Essence',
  'powers': {'signature': {'name': 'Crushing Blow',
                           'description': 'enormous weapon attack with increased weapon wear',
                           'implemented': False},
             'secondary': {'name': 'Charge',
                           'description': 'rush and slam into a target',
                           'implemented': False},
             'passive': {'name': 'Powerful Build',
                         'description': 'better heavy weapons, carrying capacity and physical force',
                         'implemented': False}}}]
